variables:
  deployment: "${CI_PROJECT_NAME}"
  image: "${CI_REGISTRY}/wms/log-be:${CI_COMMIT_SHORT_SHA}"
  namespace: "wms"

image: docker
services:
  - docker
stages:   
  - Sonar


Sonar:
  stage: Sonar
  variables:
      GIT_STRATEGY: clone
  allow_failure: true
  tags:
    - dev-wms-shell
  script:
  - docker build --rm --build-arg SONAR_HOST_URL=$SONAR_HOST_URL --build-arg SONAR_TOKEN=$SONAR_TOKEN --build-arg CI_COMMIT_TAG=$CI_COMMIT_TAG --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA --build-arg CI_PROJECT_NAME=$CI_PROJECT_NAME  --network host --add-host=$SONAR_HOST -t "${CI_REGISTRY}/wms/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}" -f Dockerfile-sonar .
  only:
    # - master
    - tags



