FROM node:16-alpine as build
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN yarn config set network-timeout 600000 -g && yarn install --production
WORKDIR /opt/app
COPY ./ .
RUN yarn build

FROM sonarsource/sonar-scanner-cli:latest
WORKDIR /opt/app
COPY --from=build /opt/node_modules ./node_modules
COPY --from=build /opt/app ./
ARG SONAR_HOST_URL
ARG SONAR_TOKEN
ARG CI_COMMIT_TAG
ARG CI_COMMIT_SHORT_SHA
ARG CI_PROJECT_NAME
RUN sonar-scanner -Dsonar.projectKey=develop -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=. -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.projectVersion=${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}


